instrumentation:
  root: ./src/
  extensions:
  - '.ts'
  - '.tsx'
  include-all-sources: true
  excludes:
  - '*.test.ts'
  - '*.test.tsx'
reporting:
  print: 'summary'
  reports:
  - 'cobertura'
  - 'text'
  - 'html'
  dir: './coverage'
